name: E2E
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  create-cluster:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - run: |
          GOBIN="$HOME"/bin make build-cli
          chmod 755 main.o
          mv main.o /usr/local/bin/test
      - name: Setup xvfb for screen 0
        run: Xvfb :1 -screen 0 1600x1200x24 &
      - run: /usr/local/bin/test
        env:
          DISPLAY: :1
      - name: Tear down xvfb
        run: killall Xvfb
